Merge r1407459, r1407460, r1419781, r1418524, r1401448, r1405407, r1405973, r1419726, r1418769, r1417197 from trunk:
remove warning:
mod_remoteip.c:404:38: warning: data argument not used by format string [-Wformat-extra-args]
It's a hack, but maintain the orig hack ;)

Remove warnings
mod_speling.c:400:41: warning: data argument not used by format string [-Wformat-extra-args]
                          r->uri, nuri, ref);
                                                                                                                        mod_speling.c:508:53: warning: data argument not used by format string [-Wformat-extra-args]
                          r->uri, candidates->nelts, ref);

Use 'apr_is_empty_table()' instead of testing against 'apr_table_elts(...)->nelts'

Use ap_rputs instead of ap_rvputs where applicable.

No need to apr_pstrdup things here, 'apr_socket_accept_filter' already makes it own copy.

Not compiled nor tested as on my system APR_HAS_SO_ACCEPTFILTER is set to 0.

revert r1401448 and add a comment on why there's a bewildering copy
of args passed to apr_socket_accept_filter()


cppCheck: kill two warnings about incorrect printf parameters.
'worker_thread_count' is unsigned

cppCheck: same expression on both side of '|'.
Fix it the same way other messages are managed in the function.

Fix a few 'too many arguments for format' warnings


cppCheck: kill a unread variable warning
Submitted by: jim, jailletc36, jailletc36, jailletc36, trawick, jailletc36, jailletc36, sf, jailletc36
Reviewed/backported by: jim


git-svn-id: https://svn.apache.org/repos/asf/httpd/httpd/branches/2.4.x@1420696 13f79535-47bb-0310-9956-ffa450edef68